In [1]:
import pandas as pd
import numpy as np
from surprise import Reader,Dataset,SVD
import pickle
import os

In [2]:
modify_path = "../CineIq_Data/modify/"
ratings_path = "../CineIq_Data/ml-25m/ratings.csv"
movies_path  = "../CineIq_Data/modify/cineiq_metadata.csv"
ratings = pd.read_csv(ratings_path).drop(columns=["timestamp"]).sample(n=1000000, random_state=42)
movies = pd.read_csv(movies_path)[["movieId","title"]]

In [3]:
ratings.head()

          userId  movieId  rating
15347762   99476   104374     3.5
16647840  107979     2634     4.0
23915192  155372     1614     3.0
10052313   65225     7153     4.0
12214125   79161      500     5.0

In [4]:
movies.head()

   movieId                               title
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

In [5]:
reader = Reader(rating_scale=(0.5,5.0))
data = Dataset.load_from_df(ratings,reader)
trainset = data.build_full_trainset()
svd_model = SVD(n_factors=100, random_state=42)
svd_model.fit(trainset)

In [6]:
os.makedirs(modify_path, exist_ok=True)
with open(modify_path + "svd_model.pkl", "wb") as f:
    pickle.dump(svd_model,f)